FROM continuumio/miniconda3:25.3.1-1

LABEL author="conanyangqun"
LABEL github="https://github.com/conanyangqun/container-for-bioinformatics"

RUN conda install -c conda-forge -c bioconda -c nanoporetech -y python==3.10 medaka==2.0.1
