FROM continuumio/miniconda3:25.1.1-2

LABEL author="conanyangqun"
LABEL github="https://github.com/conanyangqun/container-for-bioinformatics"

RUN conda install -y -c conda-forge -c bioconda python==3.9.0 graphaligner==1.0.20
