FROM continuumio/miniconda3:25.3.1-1

LABEL author="conanyangqun"
LABEL github="https://github.com/conanyangqun/container-for-bioinformatics"

RUN conda install -c conda-forge -c bioconda -y python==3.10 freyja==1.5.3
