FROM continuumio/miniconda3:25.3.1-1

LABEL author="conanyangqun"
LABEL github="https://github.com/conanyangqun/container-for-bioinformatics"

RUN conda install -y -c conda-forge -c bioconda python==3.10 flye==2.9.6
